movie/urls.py
from django.urls import path

from movie.views import (
    MovieListView,
    MoviesFilterView,
    MovieSearchView,
    MovieDetailView,
    MovieCreateView,
    MovieFramesCreateView,
    ReviewCreateView,
    DirectorView,
    DirectorCreateView,
    DirectorUpdateView,
    ActorView,
    ActorCreateView,
    ActorUpdateView,
    CategoryDetailView,
    AddCategoryView,
    GenreCreateView,
)

app_name = "movie"


urlpatterns = [
    path("", MovieListView.as_view(), name="movie-list"),
    path("movie/create/", MovieCreateView.as_view(), name="movie-create"),
    path(
        "movie-frame/create/",
        MovieFramesCreateView.as_view(),
        name="movie-frame-create"
    ),
    path("movie-filter/", MoviesFilterView.as_view(), name="movie-filter"),
    path("movie-search/", MovieSearchView.as_view(), name="movie-search"),
    path("<slug:slug>/", MovieDetailView.as_view(), name="movie-detail"),
    path("<slug:slug>/rating/", MovieDetailView.as_view(), name="add-rating"),
    path("review/<int:pk>/", ReviewCreateView.as_view(), name="review-create"),
    path(
        "director/create/",
        DirectorCreateView.as_view(),
        name="director-create"
    ),
    path(
        "director/<str:slug>/",
        DirectorView.as_view(),
        name="director-detail"
    ),
    path(
        "director/<str:slug>/update/",
        DirectorUpdateView.as_view(),
        name="director-update"
    ),
    path("actor/create/", ActorCreateView.as_view(), name="actor-create"),
    path("actor/<str:slug>/", ActorView.as_view(), name="actor-detail"),
    path(
        "actor/<str:slug>/update/",
        ActorUpdateView.as_view(),
        name="actor-update"
    ),
    path(
        "category/create/",
        AddCategoryView.as_view(),
        name="category-create"
    ),
    path(
        "category/<slug:slug>/",
        CategoryDetailView.as_view(),
        name="category-movies"
    ),
    path("genre/create/", GenreCreateView.as_view(), name="genre-create"),
]

movie_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import ChangePasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls", namespace="movie")),
    path("user/", include("user.urls", namespace="user")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "<int:pk>/password/",
        ChangePasswordView.as_view(),
        name="password-change"
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user.views import (
    UserRegisterView,
    UserEditView,
    UserProfileCreateView,
    ProfileEditView,
    password_success_view,
    ResetPasswordView,
    ResetPasswordDoneView,
    ResetPasswordConfirmView,
    ResetPasswordCompleteView,
)


app_name = "user"


urlpatterns = [
    path(
        "register/",
        UserRegisterView.as_view(),
        name="register"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="registration/logout.html"
        ),
        name="logout",
    ),
    path(
        "edit-user-data/",
        UserEditView.as_view(),
        name="edit-user-data"
    ),
    path(
        "<int:pk>/edit-profile/",
        ProfileEditView.as_view(),
        name="edit-profile"
    ),
    path(
        "profile-create/",
        UserProfileCreateView.as_view(),
        name="profile-create"
    ),
    path(
        "password-success/",
        password_success_view,
        name="password-success"
    ),
    path(
        "reset_password/",
        ResetPasswordView.as_view(),
        name="reset_password"
    ),
    path(
        "reset_password_sent/",
        ResetPasswordDoneView.as_view(),
        name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/",
        ResetPasswordConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "reset_password_complete/",
        ResetPasswordCompleteView.as_view(),
        name="password_reset_complete"
    ),
]

movie/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("movie:category-movies", kwargs={"slug": self.slug})


class Genre(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveSmallIntegerField(default=0)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="directors/", null=True, blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("movie:director-detail", kwargs={"slug": self.name})


class Actor(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveSmallIntegerField(default=0)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="actors/", null=True, blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("movie:actor-detail", kwargs={"slug": self.name})


class Movie(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    tagline = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    poster = models.ImageField(upload_to="movies/", null=True, blank=True)
    year_of_release = models.PositiveSmallIntegerField(default=2023)
    country = models.CharField(max_length=255, blank=True)
    directors = models.ManyToManyField(Director, related_name="film_director")
    actors = models.ManyToManyField(Actor, related_name="film_actor")
    genres = models.ManyToManyField(Genre, related_name="film_genre")
    world_premiere = models.DateField(null=True, blank=True)
    budget = models.PositiveIntegerField(
        default=0, help_text="Enter amount in dollars"
    )
    fees_in_the_usa = models.PositiveIntegerField(
        default=0, help_text="Enter amount in dollars"
    )
    fees_in_the_world = models.PositiveIntegerField(
        default=0, help_text="Enter amount in dollars"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        related_name="film_category"
    )

    class Meta:
        ordering = ("title",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie:movie-detail", kwargs={"slug": self.slug})

    def get_review(self):
        return self.film_review.filter(parent__isnull=True)


class MovieFrames(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="movie_frames/", null=True, blank=True)
    movies = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="film_frames"
    )

    class Meta:
        ordering = ("title",)
        verbose_name = "Movie frame"
        verbose_name_plural = "Movie frames"

    def __str__(self):
        return self.title


class Rating(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user_rating"
    )
    rating = models.IntegerField(default=1)
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="film_rating"
    )

    def __str__(self):
        return f"{self.rating} - {self.movie}"


class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user_review"
    )
    text = models.TextField(blank=True)
    parent = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Parent"
    )
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="film_review"
    )

    def __str__(self):
        return f"{self.user} - {self.movie}"

movie/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from movie.models import Review, Movie


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ("user", "text",)


class MovieForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Movie
        fields = (
            "title",
            "slug",
            "tagline",
            "description",
            "poster",
            "year_of_release",
            "country",
            "directors",
            "actors",
            "genres",
            "world_premiere",
            "budget",
            "fees_in_the_usa",
            "fees_in_the_world",
            "category",
        )


class RatingForm(forms.Form):
    rating = forms.IntegerField(
        label="Rating",
        min_value=1,
        max_value=5,
        widget=forms.NumberInput(attrs={"class": "rating-input"}),
    )

templates/movie/actor.html
{% extends "base.html" %}

{% block title %}{{ actor.name }}{% endblock %}

{% block content %}

  <div class="col-lg-1"></div>

  <div class="left-ads-display col-lg-7">

    <h1><strong>Actor: </strong> <em>{{ actor.name }}</em>
      <a href="{% url 'movie:actor-update' actor.name %}" class="btn btn-warning link-to-page" style="float: right">
        Edit
      </a>
    </h1>
    <hr>
    <br>

    <div class="row">
      <div class="desc1-left col-md-6">
        <img src="{{ actor.image.url}}" class="img-fluid" alt="" width="800px">
      </div>
      <div class="desc1-right col-md-6 pl-lg-4">

        <h5 class="editContent"></h5>
        <ul>
          <li style="list-style: none">
            <span><b>Age:</b> {{ actor.age }}</span>
          </li>

          <li style="list-style: none">
            <span><b>Starred in the films:</b><br>
              {% for movie in actor.film_actor.all %}
                &#8195;&#8195;- {{ movie.title }}<br>
              {% endfor %}
            </span>
          </li>
        </ul>
      </div>
    </div>

    <div class="row sub-para-w3layouts mt-5">

      <h2 class="shop-sing editContent" style="outline: none; cursor: inherit;">
        About &#8194;<em>{{ actor.name }}</em>
      </h2>
      <hr>

      <p class="editContent" style="outline: none; cursor: inherit;">
        {{ actor.description|safe }}
      </p>

    </div>
  </div>

{% endblock %}

templates/movie/add_category.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Create A New Category{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    {% if user.is_authenticated %}

      <h1>Add Category...</h1>
      <br>

      <form action="{% url 'movie:category-create' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button  class="btn btn-warning">Add Category</button>
      </form>

    {% else %}
      <h5>You're not allowed here!&#8194;<small><em>(And you know it...)</em></small></h5>

    {% endif %}
  </div>

{% endblock %}

templates/movie/add_genre.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add A New Genre{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    {% if user.is_staff %}

      <h1>Add a Genre...</h1>
      <br>

      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button  class="btn btn-warning">Add Genre</button>
      </form>

    {% else %}
      <h5>You're not allowed here!&#8194;<small><em>(And you know it...)</em></small></h5>

    {% endif %}

  </div>

{% endblock %}

templates/movie/add_movie.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Create A New Movie{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    {% if user.is_staff %}
      <h1>Add Movie...</h1>
      <br>

      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button  class="btn btn-warning">Add Movie</button>
      </form>

    {% else %}
      <h5>You're not allowed here!</h5>&#8194;
      <p><em>(and you know it...)</em></p>
    {% endif %}

  </div>

{% endblock %}

templates/movie/add_movie_frame.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add New Movie Frames{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    {% if user.is_staff %}

      <h1>Add Movie Frame...</h1>
      <br>

      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button  class="btn btn-warning">Add Movie Frame</button>
      </form>

    {% else %}
      <h5>You're not allowed here!&#8194;<small><em>(And you know it...)</em></small></h5>

    {% endif %}

      </div>

{% endblock %}

templates/movie/add_or_edit_actor.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add A New Actor{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    {% if user.is_staff %}

      <h1>{{ object|yesno:"Edit,Add" }} an Actor...</h1>
      <br>

      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button  class="btn btn-warning">{{ object|yesno:"Edit,Add" }} Actor</button>
      </form>

    {% else %}
      <h5>You're not allowed here!&#8194;<small><em>(And you know it...)</em></small></h5>

    {% endif %}

  </div>

{% endblock %}

templates/movie/add_or_edit_director.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add A New Director{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    {% if user.is_staff %}

      <h1>{{ object|yesno:"Edit,Add" }} a Director...</h1>
      <br>

      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button  class="btn btn-warning">{{ object|yesno:"Edit,Add" }} Director</button>
      </form>

    {% else %}
      <h5>You're not allowed here!&#8194;<small><em>(And you know it...)</em></small></h5>

    {% endif %}

  </div>

{% endblock %}

templates/movie/director.html
{% extends "base.html" %}

{% block title %}{{ director.name }}{% endblock %}

{% block content %}

  <div class="col-lg-1"></div>

  <div class="left-ads-display col-lg-7">

    <h1><strong>Director: </strong> <em>{{ director.name }}</em>
      <a href="{% url 'movie:director-update' director.name %}" class="btn btn-warning link-to-page" style="float: right">
        Edit
      </a>
    </h1>
    <hr>
    <br>

    <div class="row">
      <div class="desc1-left col-md-6">
        <img src="{{ director.image.url }}" class="img-fluid" alt="" width="800px">
      </div>
      <div class="desc1-right col-md-6 pl-lg-4">

        <h5 class="editContent"></h5>
        <ul>
          <li style="list-style: none">
            <span><b>Age:</b> {{ director.age }}</span>
          </li>

          <li style="list-style: none">
            <span><b>Directed films:</b><br>
              {% for movie in director.film_director.all %}
                &#8195;&#8195;- {{ movie.title }}<br>
              {% endfor %}
            </span>
          </li>
        </ul>
      </div>
    </div>

    <div class="row sub-para-w3layouts mt-5">

      <h2 class="shop-sing editContent" style="outline: none; cursor: inherit;">
        About &#8194;<em>{{ director.name }}</em>
      </h2>
      <hr>

      <p class="editContent" style="outline: none; cursor: inherit;">
        {{ director.description|safe }}
      </p>

    </div>
  </div>

{% endblock %}

templates/movie/movie_detail.html
{% extends "base.html" %}

{% load movie_tag %}

{% block title %}{{ movie.title }}{% endblock %}


{% block content %}

  <div class="col-lg-1"></div>

  <div class="left-ads-display col-lg-7">
    <div class="row">
      <h3>
        Title: <em>"{{ movie.title }}"</em>
      </h3>
      <hr>
      <br>

      <div class="desc1-left col-md-5">
        <img src="{{ movie.poster.url }}" class="img-fluid" alt="" width="800px">
      </div>

      <div class="desc1-right col-md-6 pl-lg-4">

        <ul>
          <li style="list-style: none">
            <span><b>Year:</b> {{ movie.year_of_release }}</span>
          </li>
          <li style="list-style: none">
            <span><b>Country:</b> {{ movie.country }}</span>
          </li>
          <li style="list-style: none">
            <span><b>Tagline:</b> <em>"{{ movie.tagline }}"</em></span>
          </li>
          <li style="list-style: none">
            <span><b>Director:</b>
              {% for director in movie.directors.all %}
                <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
              {% endfor %}
            </span>
          </li>
          <li style="list-style: none">
            <span><b>Actors:</b><br>
              {% for actor in movie.actors.all %}
                &#8195;<a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a><br>
              {% endfor %}
            </span>
          </li>
          <li style="list-style: none">
            <span><b>Genre:</b><br>
              {% for genre in movie.genres.all %}
                &#8195;{{ genre.name }}<br>
              {% endfor %}
            </span>
          </li>
          <li style="list-style: none">
            <span><b>The premiere in the world:</b> {{ movie.world_premiere }}</span>
          </li>
          <li style="list-style: none">
            <span><b>Budget:</b> ${{ movie.budget }}</span>
          </li>
          <li style="list-style: none">
            <span><b>Fees in the USA:</b> ${{ movie.fees_in_the_usa }}</span>
          </li>
          <li style="list-style: none">
            <span><b>Fees in the World:</b> ${{ movie.fees_in_the_world }}</span>
          </li>
        </ul>

        <br>

        <div class="rating">
          <span>&#8195;&#8195;<b>Rating:</b> </span>
          <ul class="w3layouts-box-list">
            {% if not average_rating %}
              <span class="fa fa-star-o" aria-hidden="true" ></span>
              <span class="fa fa-star-o" aria-hidden="true" ></span>
              <span class="fa fa-star-o" aria-hidden="true" ></span>
              <span class="fa fa-star-o" aria-hidden="true" ></span>
              <span class="fa fa-star-o" aria-hidden="true" ></span>
            {% else %}
              {% if average_rating == 1 %}
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
              {% endif %}

              {% if average_rating == 2 %}
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
              {% endif %}

              {% if average_rating == 3 %}
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
              {% endif %}

              {% if average_rating == 4 %}
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star-o" aria-hidden="true" ></span>
              {% endif %}

              {% if average_rating == 5 %}
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
                <span class="fa fa-star" aria-hidden="true" ></span>
              {% endif %}
            {% endif %}
            <span class="editContent" > &#8194;<small>{{ average_rating }}.0</small></span>

          </ul>
        </div>

        <br>

        <div class="share-desc">
          <div class="share">
            <h4 class="editContent" style="outline: none; cursor: inherit;"> &#8195;&#8195;<strong>Share:</strong></h4>
            <ul class="w3layouts_social_list list-unstyled">&#8195;
              <li>
                <a href="#" class="w3pvt_facebook editContent" style="outline: none; cursor: inherit;">
                  <span class="fa fa-facebook-f" style="outline: none; cursor: inherit;"></span>
                </a>
              </li>
              <li>
                <a href="#" class="w3pvt_twitter editContent" style="outline: none; cursor: inherit;">
                  <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                </a>
              </li>
              <li>
                <a href="#" class="w3pvt_google editContent" style="outline: none; cursor: inherit;">
                  <span class="fa fa-instagram" style="outline: none; cursor: inherit;"></span>
                </a>
              </li>
              <li>
                <a href="#" class="w3pvt_twitter editContent" style="outline: none; cursor: inherit;">
                  <span class="fa fa-telegram" style="outline: none; cursor: inherit;"></span>
                </a>
              </li>
              <li>
                <a href="#" class="w3pvt_dribble editContent" style="outline: none; cursor: inherit;">
                  <span class="fa fa-dribbble" style="outline: none; cursor: inherit;"></span>
                </a>
              </li>
            </ul>
          </div>
          <div class="clearfix"></div>
        </div>

      </div>
    </div>

    <div class="row sub-para-w3layouts mt-5">

      <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
        About the movie <em>"{{ movie.title }}"</em>
      </h3>&#8195;&#8195;&#8195;&#8195;&#8195;&#8195;
      <p>
        {% for image in movie.film_frames.all %}
          <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.description }}" width="120">
        {% endfor %}
      </p><br>
      <p class="editContent" style="outline: none; cursor: inherit;">
        {{ movie.description|safe }}
      </p>

    </div>

    <hr>

    {% if user.is_authenticated %}
    <div class="row">
      <div class="single-form-left">
        <!-- contact form grid -->
        <div class="contact-single">
          <h2 class="editContent" style="outline: none; cursor: inherit;">
            <span class="sub-tittle editContent" style="outline: none; cursor: inherit;">
              <small>{{ movie.film_review.count }}</small>
            </span>
            Leave a review
          </h2>

          <form action="{% url 'movie:review-create' movie.id %}" method="post" class="mt-4" id="formReview">
            {% csrf_token %}
            <input type="hidden" name="parent" id="contactparent" value="">
            <div class="form-group editContent">

              <label for="contactcomment" class="editContent">
                Your comment*
              </label>
              <textarea class="form-control border" rows="5"
                        id="contactcomment" required="" name="text">
              </textarea>
            </div>
            <div class="d-sm-flex">
              <div class="col-sm-6 form-group p-0 editContent" style="outline: none; cursor: inherit;">
                <label for="contactusername" class="editContent">
                  Name*
                </label>
                <input type="text" class="form-control border"
                       id="contactusername" required=""
                       name="first_name" value="{{ request.user.first_name }}"
                       readonly
                >
              </div>&#8194;
              <div class="col-sm-6 form-group ml-sm-3 editContent" style="outline: none; cursor: inherit;">
                <label for="contactemail" class="editContent">
                  Email*
                </label>
                <input type="email" class="form-control border"
                       id="contactemail" required=""
                       name="email" value="{{ request.user.email }}"
                       readonly
                >
              </div>
            </div>
            <br>
            <button type="submit" class="btn btn-warning" style="outline: none; cursor: inherit; font-size: 20px">Submit</button>
          </form>

        </div>
        <!--  //contact form grid ends here -->
      </div>
    </div>


    <br>
    <hr>
    <div class="rating">
      <form method="post" action="{% url 'movie:add-rating' movie.slug %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-warning">Submit Rating</button>
      </form>
    </div>
  {% endif %}

    <br><br>
    <hr>
    <div>

      <h3 class="editContent" style="outline: none; cursor: inherit;">
        <span class="sub-tittle editContent" style="outline: none; cursor: inherit;"></span>
        Comments
      </h3>
      <hr>
      {% for review in movie.get_review %}
        <div class="media py-5">

          <img src="{{ review.user.profile.image.url }}" class="mr-3 img-fluid" alt="image" width="80">&#8195;&#8195;&#8195;
          <div class="media-body mt-4">
            <h5 class="mt-0 editContent">{{ review.user.first_name }}</h5>
            <p class="mt-2 editContent" style="outline: none; cursor: inherit;">{{ review.text }}</p>

            {% if user.is_authenticated %}
              {% if review.user != request.user %}
              <a href="#formReview"
                 onclick="addReview('{{ review.user.first_name }}','{{ review.id }}')">
                Answer
              </a>
              {% endif %}
            {% endif %}

            {% for rew in review.review_set.all %}
              <div class="media mt-5 editContent">
                <div class="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-10">
                    <a class="pr-3" href="#">
                      <img src="{{ rew.user.profile.image.url }}" class="img-fluid" alt="image" width="80">
                    </a>
                    <div class="media-body">
                      <h5 class="mt-0 editContent">{{ rew.user.first_name }}</h5>
                      <p class="mt-2 editContent">{{ rew.text }}</p>
                    </div>
                  </div>
                </div>
              </div>

            {% endfor %}

          </div>

        </div><hr>
      {% endfor %}
    </div>

  </div>

  <script>
    function addReview(first_name, id) {
      document.getElementById("contactparent").value = id;
      document.getElementById("contactcomment").innerText = `${first_name}, `
    }
  </script>

  <br><br>

{% endblock %}