movie/urls.py
from django.urls import path

from movie.views import (
    MovieListView,
    MoviesFilterView,
    MovieSearchView,
    MovieDetailView,
    MovieCreateView,
    MovieFramesCreateView,
    ReviewCreateView,
    DirectorView,
    DirectorCreateView,
    DirectorUpdateView,
    ActorView,
    ActorCreateView,
    ActorUpdateView,
    CategoryDetailView,
    AddCategoryView,
    GenreCreateView,
)

app_name = "movie"


urlpatterns = [
    path("", MovieListView.as_view(), name="movie-list"),
    path("movie/create/", MovieCreateView.as_view(), name="movie-create"),
    path(
        "movie-frame/create/",
        MovieFramesCreateView.as_view(),
        name="movie-frame-create"
    ),
    path("movie-filter/", MoviesFilterView.as_view(), name="movie-filter"),
    path("movie-search/", MovieSearchView.as_view(), name="movie-search"),
    path("<slug:slug>/", MovieDetailView.as_view(), name="movie-detail"),
    path("<slug:slug>/rating/", MovieDetailView.as_view(), name="add-rating"),
    path("review/<int:pk>/", ReviewCreateView.as_view(), name="review-create"),
    path(
        "director/create/",
        DirectorCreateView.as_view(),
        name="director-create"
    ),
    path(
        "director/<str:slug>/",
        DirectorView.as_view(),
        name="director-detail"
    ),
    path(
        "director/<str:slug>/update/",
        DirectorUpdateView.as_view(),
        name="director-update"
    ),
    path("actor/create/", ActorCreateView.as_view(), name="actor-create"),
    path("actor/<str:slug>/", ActorView.as_view(), name="actor-detail"),
    path(
        "actor/<str:slug>/update/",
        ActorUpdateView.as_view(),
        name="actor-update"
    ),
    path(
        "category/create/",
        AddCategoryView.as_view(),
        name="category-create"
    ),
    path(
        "category/<slug:slug>/",
        CategoryDetailView.as_view(),
        name="category-movies"
    ),
    path("genre/create/", GenreCreateView.as_view(), name="genre-create"),
]

movie_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import ChangePasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls", namespace="movie")),
    path("user/", include("user.urls", namespace="user")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "<int:pk>/password/",
        ChangePasswordView.as_view(),
        name="password-change"
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user.views import (
    UserRegisterView,
    UserEditView,
    UserProfileCreateView,
    ProfileEditView,
    password_success_view,
    ResetPasswordView,
    ResetPasswordDoneView,
    ResetPasswordConfirmView,
    ResetPasswordCompleteView,
)


app_name = "user"


urlpatterns = [
    path(
        "register/",
        UserRegisterView.as_view(),
        name="register"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="registration/logout.html"
        ),
        name="logout",
    ),
    path(
        "edit-user-data/",
        UserEditView.as_view(),
        name="edit-user-data"
    ),
    path(
        "<int:pk>/edit-profile/",
        ProfileEditView.as_view(),
        name="edit-profile"
    ),
    path(
        "profile-create/",
        UserProfileCreateView.as_view(),
        name="profile-create"
    ),
    path(
        "password-success/",
        password_success_view,
        name="password-success"
    ),
    path(
        "reset_password/",
        ResetPasswordView.as_view(),
        name="reset_password"
    ),
    path(
        "reset_password_sent/",
        ResetPasswordDoneView.as_view(),
        name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/",
        ResetPasswordConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "reset_password_complete/",
        ResetPasswordCompleteView.as_view(),
        name="password_reset_complete"
    ),
]

templates/includes/footer.html
<!-- footer -->
{% load subscribe_tags %}

<footer class="editContent">
  <div class="container">
    <div class="row footer-top">
      <div class="col-lg-4 footer-grid_section_w3layouts">
        <h2 class="logo-2 mb-lg-4 mb-3">
          <a href="#" class="editContent">
            <span class="fa" aria-hidden="true" >
              Movie World
            </span>
          </a>
        </h2>
        <p class="editContent" >
          Movie World is located in Oxenford on the Gold Coast, Queensland, approximately 20 km (13 miles) from Surfers Paradise.
          It is part of a 154-hectare (380.5-acre) precinct that includes three other Village properties: Wet'n'Wild Gold Coast,
          Australian Outback Spectacular and Paradise Country. The 15 attractions can be divided into five broad areas: Main Street,
          Kids' WB Fun Zone, the wild west, DC Comics Super-Villains Unleashed and the DC Comics superhero hub.
        </p>
        <h4 class="sub-con-fo ad-info my-4 editContent" >Catch on Social</h4>
        <ul class="w3layouts_social_list media-soc list-unstyled">
          <li>
            <a href="#" class="w3pvt_facebook editContent" >
              <span class="fa fa-facebook-f" ></span>
            </a>
          </li>
          <li>
            <a href="#" class="w3pvt_twitter editContent" >
              <span class="fa fa-twitter" ></span>
            </a>
          </li>
          <li>
            <a href="#" class="w3pvt_google editContent" >
              <span class="fa fa-instagram" ></span>
            </a>
          </li>
          <li>
            <a href="#" class="w3pvt_twitter editContent" >
              <span class="fa fa-telegram" aria-hidden="true"></span>
            </a>
          </li>
          <li>
            <a href="#" class="w3pvt_dribble editContent" >
              <span class="fa fa-dribbble" ></span>
            </a>
          </li>
          <li>
            <a href="#" class="w3pvt_google editContent" >
              <span class="fa fa-google-plus" ></span>
            </a>
          </li>
        </ul>
      </div>

      <div class="col-lg-1"></div>

      <div class="col-lg-7 footer-right">

        {% if user.is_authenticated %}
        <div class="w3layouts-news-letter">
          {% get_subscribe_form request.user %}
        </div>
        {% endif %}


        <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
          <div class="col-md-4 footer-grid_section_w3layouts">
            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Sections</h3>
            <ul class="list-unstyled w3layouts-icons">
              <li>
                <a href="/" class="editContent" > Frontpage</a>
              </li>
              <li>
                <a href="#" class="editContent" >Categories</a>
              </li>
              <li>
                <a href="#" class="editContent" >Contacts</a>
              </li>
            </ul>
          </div>
          <div class="col-md-4 footer-grid_section_w3layouts">
            <!-- social icons -->
            <div class="agileinfo_social_icons">
              <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Pages</h3>
              <ul class="list-unstyled w3layouts-icons">

                <li>
                  <a href="#" class="editContent" >About Us</a>
                </li>

              </ul>
            </div>
            <!-- social icons -->
          </div>
          <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
            <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent" >Contact Info</h3>
            <div class="contact-info">
              <div class="footer-address-inf my-4">
                <h4 class="ad-info mb-2 editContent" >Email </h4>
                <p class="editContent" ><a href="mailto:info@example.com">info@example.com</a></p>
              </div>
              <div class="footer-address-inf">
                <h4 class="ad-info mb-2 editContent" >Location</h4>
                <p class="editContent" >Oxenford, Australia</p>
              </div>
            </div>
          </div>


        </div>

      </div>
    </div>
  </div>
</footer>
<!-- //footer -->
<div class="cpy-right py-3">
  <div class="container">
    <div class="row">
      <p class="col-md-10 text-center">© 2023 MovieWorld. All rights reserved.
        <a href="#"></a>
      </p>
      <!-- move top icon -->
      <a href="#" class="move-top text-right col-md-2"><span class="fa fa-long-arrow-up" aria-hidden="true" ></span></a>
      <!-- //move top icon -->
    </div>
  </div>
</div>

templates/includes/navigation.html
{% load static %}
{% load movie_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-blue fixed-top">&#8195;&#8195;
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img class="img" src="/static/images/movie_world.jpg" alt="" width="40" style="border-radius: 50%">&#8194;<strong><em>MovieWorld</em></strong></a>&#8195;&#8195;&#8195;
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/" style="color: #902b2b; font-size: 24px"><strong>Home</strong></a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% get_categories as categories %}
              {% for category in categories %}
            <li><a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
              {% endfor %}
            {% if user.is_staff %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'movie:category-create' %}">Add category</a></li>
            {% endif %}
          </ul>
        </li>

        {% if user.is_staff %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Movies
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'movie:genre-create' %}">Add Genre</a></li>
            <li><a class="dropdown-item" href="{% url 'movie:director-create' %}">Add Director</a></li>
            <li><a class="dropdown-item" href="{% url 'movie:actor-create' %}">Add Actor</a></li>
            <li><a class="dropdown-item" href="{% url 'movie:movie-create' %}">Add Movie</a></li>
            <li><a class="dropdown-item" href="{% url 'movie:movie-frame-create' %}">Add Movie Frame</a></li>
          </ul>
        </li>
        {% endif %}

      </ul>

      {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hello, <em>{{ user.first_name }}</em>
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'user:edit-user-data' %}">Edit Settings</a></li>
            {% if user.profile.id %}
            <li><a class="dropdown-item" href="{% url 'user:edit-profile' user.profile.id %}">Edit Profile</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'user:profile-create' %}">Create Profile</a></li>
            {% endif %}
            {% if user.is_staff %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a></li>
            {% endif %}
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a></li>
          </ul>
        </li>

        <span>
          <img src="{% if user.profile.image %}{{ user.profile.image.url }}
               {% else %}{% static 'images/user.png' %}{% endif %}" alt=""
               width="36" style="border-radius: 50%">
        </span>

      {% else %}
        &#8194;
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Sign up</a>
        </li>
        &#8194;&#8194;
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">Sign in</a>
        </li>
      </ul>&#8195;&#8195;
    {% endif %}

    </div>
  </div>
</nav>


<br><br><br>
<div class="banner-info">
  <h3 class="mb-4">Everything about the cinema</h3>
</div>

templates/includes/pagination.html
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-8">

      <div class="pagination justify-content-center">
        {% if page_obj.has_other_pages %}

          {% if page_obj.has_previous %}

            <a class="btn btn-outline-warning mb-4 mr-1" href="?page=1">&laquo;</a>
            <a class="btn btn-outline-warning mb-4 mr-1" href="?{{ q }}{{ genres }}{{ year_of_release }}page={{ page_obj.previous_page_number }}">&#8249;</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="btn btn-warning mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <a class="btn btn-outline-warning mb-4 mr-1" href="?{{ q }}{{ genres }}{{ year_of_release }}page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="btn btn-outline-warning mb-4 mr-1" href="?{{ q }}{{ genres }}{{ year_of_release }}page={{ page_obj.next_page_number }}">&#8250;</a>
            <a class="btn btn-outline-warning mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
          {% endif %}

        {% endif %}
      </div>

    </div>
  </div>
</div>

templates/includes/sidebar.html
{% load movie_tag %}
  <div class="search-bar w3layouts-newsletter">
    <h3 class="sear-head editContent" >Movie search</h3>
    <form action="{% url 'movie:movie-search' %}" method="get" class="d-flex editContent" >
      <label>
        <input type="search" placeholder="Enter a name..." name="q" class="form-control" required="">
      </label>&#8194;
      <button type="submit" class="btn btn-warning" >
        <span class="fa fa-search" aria-hidden="true" ></span>
      </button>
    </form>
  </div>
  <!--preference -->
  <form action="{% url 'movie:movie-filter' %}" method="get">
    <div class="left-side my-4">
      <h3 class="sear-head editContent" >Genres</h3>
      <ul class="w3layouts-box-list">
        {% for genre in view.get_genres %}
        <li class="editContent" >
          <label>
            <input type="checkbox" class="checked" name="genres" value="{{ genre.id }}">
          </label>
          <span class="span editContent" > &#8194;{{ genre.name }}</span>
        </li>
        {% endfor %}
      </ul>
    </div>
    <br>
  <!-- // preference -->
  <!-- discounts -->

    <div class="left-side">
      <h3 class="sear-head editContent" >Years</h3>
      <ul class="w3layouts-box-list">
        {% for movie in view.get_years_release %}
        <li class="editContent" >
          <label>
            <input type="checkbox" class="checked" name="year_of_release" value="{{ movie.year_of_release }}">
          </label>
          <span class="span editContent" > &#8194;{{ movie.year_of_release }}</span>
        </li>
        {% endfor %}
      </ul>
    </div>
    <br>

    <button type="submit" class="btn btn-warning">Submit</button>
  </form>
  <hr>

  <!-- //discounts -->


  <!-- reviews -->
  <div class="customer-rev left-side my-4">
    <h3 class="sear-head editContent" >Rating</h3>
    <ul class="w3layouts-box-list">
      <li>
        <a href="#">
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="editContent" > &#8194;<small>5.0</small></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="editContent" > &#8194;<small>4.0</small></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="editContent" > &#8194;<small>3.0</small></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true"></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="editContent" > &#8194;<small>2.0</small></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-star" aria-hidden="true"></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="editContent" > &#8194;<small>1.0</small></span>
        </a>
      </li>
      <li>
        <a href="#">
          <span class="fa fa-star-o" aria-hidden="true"></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="fa fa-star-o" aria-hidden="true" ></span>
          <span class="editContent" > &#8194;<small>0.0</small></span>
        </a>
      </li>

    </ul>
  </div>
  <hr>
  <!-- //reviews -->

{% get_last_movies count=3 %}