movie_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import ChangePasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls", namespace="movie")),
    path("user/", include("user.urls", namespace="user")),
    path("subscribe/", include("subscribe.urls", namespace="subscribe")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "<int:pk>/password/",
        ChangePasswordView.as_view(),
        name="password-change"
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user.views import (
    UserRegisterView,
    UserEditView,
    UserProfileCreateView,
    ProfileEditView,
    password_success_view,
    ResetPasswordView,
    ResetPasswordDoneView,
    ResetPasswordConfirmView,
    ResetPasswordCompleteView,
)


app_name = "user"


urlpatterns = [
    path(
        "register/",
        UserRegisterView.as_view(),
        name="register"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="registration/logout.html"
        ),
        name="logout",
    ),
    path(
        "edit-user-data/",
        UserEditView.as_view(),
        name="edit-user-data"
    ),
    path(
        "<int:pk>/edit-profile/",
        ProfileEditView.as_view(),
        name="edit-profile"
    ),
    path(
        "profile-create/",
        UserProfileCreateView.as_view(),
        name="profile-create"
    ),
    path(
        "password-success/",
        password_success_view,
        name="password-success"
    ),
    path(
        "reset_password/",
        ResetPasswordView.as_view(),
        name="reset_password"
    ),
    path(
        "reset_password_sent/",
        ResetPasswordDoneView.as_view(),
        name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/",
        ResetPasswordConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "reset_password_complete/",
        ResetPasswordCompleteView.as_view(),
        name="password_reset_complete"
    ),
]

user/models.py
from PIL import Image
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.urls import reverse
from django.utils.translation import gettext as _


class UserManager(BaseUserManager):
    """Define a model manager for User model."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="user_profile/", null=True, blank=True)
    bio = models.TextField(blank=True)

    def __str__(self):
        return f"{self.user}"

    @staticmethod
    def get_absolute_url():
        return reverse("movie:movie-list")

    def save(
        self,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None
    ):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from user.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            "email",
            "password",
            "username",
            "first_name",
            "last_name",
            "last_login",
            "is_superuser",
            "is_staff",
            "is_active",
            "date_joined"
        )

user/views.py
from django.contrib.auth.forms import (
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from user.forms import UserRegisterForm, EditProfileForm
from user.models import Profile


class UserRegisterView(SuccessMessageMixin, CreateView):
    form_class = UserRegisterForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("user:login")

    success_message = (
        "Your account is created successfully, please, "
        "login with your email and password"
    )


class UserEditView(SuccessMessageMixin, UpdateView):
    form_class = EditProfileForm
    template_name = "user/edit_user_data.html"
    success_url = reverse_lazy("movie:movie-list")

    success_message = "Your settings has been successfully updated."

    def get_object(self, queryset=None):
        return self.request.user


class UserProfileCreateView(SuccessMessageMixin, CreateView):
    model = Profile
    template_name = "user/create_user_profile_page.html"
    fields = ("bio", "image",)

    success_message = "Your profile has been successfully created."

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy("movie:movie-list")


class ProfileEditView(SuccessMessageMixin, UpdateView):
    model = Profile
    template_name = "user/edit_profile_page.html"
    fields = ("bio", "image")
    success_url = reverse_lazy("movie:movie-list")

    success_message = "Your profile has been successfully updated."


class ChangePasswordView(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = "user/password_change_form.html"
    success_url = reverse_lazy("user:password-success")


def password_success_view(request):
    return render(request, "user/password_change_done.html", {})


class ResetPasswordView(PasswordResetView):
    form_class = PasswordResetForm
    email_template_name = "user/password_reset_email.html"
    template_name = "user/password_reset_form.html"
    success_url = reverse_lazy("user:password_reset_done")


class ResetPasswordDoneView(PasswordResetDoneView):
    template_name = "user/password_reset_done.html"


class ResetPasswordConfirmView(PasswordResetConfirmView):
    form_class = SetPasswordForm
    template_name = "user/password_reset_confirm.html"
    success_url = reverse_lazy("user:password_reset_complete")


class ResetPasswordCompleteView(PasswordResetCompleteView):
    template_name = "user/password_reset_complete.html"

templates/user/create_user_profile_page.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Create User Profile{% endblock %}

{% block content %}

      <div class="col-md-1"></div>

      <div class="col-md-7">
      {% if user.is_authenticated %}

        <h1>Create User Profile Page...</h1>
        <br>

        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button  class="btn btn-warning">Create Profile</button>
        </form>

      {% else %}
        <h5>You're not allowed here!</h5>&#8194;
        <p><em>(and you know it...)</em></p>

      {% endif %}

      </div>

{% endblock %}

templates/user/edit_profile_page.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Edit Profile{% endblock %}

{% block content %}


      <div class="col-md-1"></div>

      <div class="col-md-7">
      {% if user.is_authenticated %}

        {% if user.id == profile.user.id %}

        <h1>Edit Profile...</h1>
        <br>
        <img src="{{ user.profile.image.url }}" alt="" class="rounded-circle">
        <br><br>

        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button  class="btn btn-warning">Update Profile</button>
        </form>

        {% else %}
          You're not the correct User To Edit This Page...

        {% endif %}

      {% else %}
        <h5>You're not allowed here!</h5>&#8194;
          <p><em>(and you know it...)</em></p>

      {% endif %}

      </div>

{% endblock %}

templates/user/edit_user_data.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block title %}Edit Settings{% endblock %}

{% block content %}

      <div class="col-md-1"></div>

      <div class="col-md-7">

        <h1>Edit User Settings...</h1><br><br>

        <img src="{{ user.profile.image.url }}" alt="" class="rounded-circle">
        <br><br>
        <div class="form-group">

          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-warning" type="submit">Update Settings</button>
          </form>

        </div>
      </div>

{% endblock %}

templates/user/password_change_done.html
{% extends "base.html" %}

{% block title %}Password changed{% endblock %}

{% block content %}

      <div class="col-md-1"></div>
      <div class="col-md-7">
        <h1>Password changed...</h1>
        <p>Your password has been successfully changed.</p>
      </div>

{% endblock %}

templates/user/password_change_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Change Password{% endblock %}

{% block content %}

        <div class="col-md-1"></div>
        <div class="col-md-7">
          <h1>Change you password...</h1>
          <p>Use the form below to change your password.</p><br>

          <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <p><input type="submit" value="Change"></p>
          </form>

        </div>

{% endblock %}

templates/user/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Password reset complete{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    <h1>Password reset complete</h1>
    <p>
      Your new password has been set. You can log in now on the <a href="{% url 'user:login' %}">log in page</a>.
    </p>
  </div>

{% endblock %}

templates/user/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Reset your password{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">

    <h1>Password Reset Confirm</h1>
    {% if validlink %}
      <p>Please enter your new password twice:</p>

      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit">Reset password</button>
      </form>

    {% else %}
      <p>The password reset link was invalid, possibly because it has
        already been used. <br>Please request a new password reset.</p>
    {% endif %}

  </div>

{% endblock %}

templates/user/password_reset_done.html
{% extends "base.html" %}

{% block title %}Email Sent{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">
    <h1>Check your inbox.</h1>
    <p>We've emailed you instructions for setting your password, if an account exists with the email you entered.
      You should receive them shortly.</p>
    <p>
      If you don't receive an email, please make sure you've entered the address you registered with,
      and check your spam folder.
    </p>
  </div>

{% endblock %}

templates/user/password_reset_email.html
{% autoescape off %}
Hello,

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{ domain }} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
The Website Team

{% endautoescape %}

templates/user/password_reset_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}

  <div class="col-md-1"></div>

  <div class="col-md-7">

    <h1>Forgotten your password?</h1>
    <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-warning" type="submit">Send email</button>
    </form>

  </div>

{% endblock %}